name: code-scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly
  schedule:
    - cron: '0 6 * * MON'
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  code-ql:

    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        filter: 'tree:0'
        show-progress: false

    - name: Initialize CodeQL
      uses: github/codeql-action/init@60168efe1c415ce0f5521ea06d5c2062adbeed1b # v3.28.17
      with:
        build-mode: none
        languages: 'csharp'
        queries: security-and-quality

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@60168efe1c415ce0f5521ea06d5c2062adbeed1b # v3.28.17
      with:
        category: "/language:csharp"
