name: dependency-review

on:
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          filter: 'tree:0'
          show-progress: false

      - name: Review dependencies
        uses: actions/dependency-review-action@38ecb5b593bf0eb19e335c03f97670f792489a8b # v4.7.0
