name: dependency-review

on:
  pull_request:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          filter: 'tree:0'
          show-progress: false

      - name: Review dependencies
        uses: actions/dependency-review-action@ce3cf9537a52e8119d91fd484ab5b8a807627bf8 # v4.6.0
